title: Premonition Demo Site
description: Demo site for Premonition
baseurl: "/premonition-demo"
url: ""

plugins:
  - jekyll-feed
  - premonition

collections:
  contributors:
    output: true

premonition:
  types:
    custom:
      meta:
        fa-icon: fa-bug
